# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories true

set tclUtilsPath "i:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "I:/FPGA_projects/xise_projects/puf/puf_proj/puf_proj.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "i:/FPGA_projects/xise_projects/puf/puf_proj/puf_proj.srcs/sources_1/ip/microblaze_mcs_v1_4_0/coregen.cgc"

set ipFile "i:/FPGA_projects/xise_projects/puf/puf_proj/puf_proj.srcs/sources_1/ip/microblaze_mcs_v1_4_0/microblaze_mcs_v1_4_0.xco"

set ipName "microblaze_mcs_v1_4_0"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

set bomFilePath "i:/FPGA_projects/xise_projects/puf/puf_proj/puf_proj.srcs/sources_1/ip/microblaze_mcs_v1_4_0/pa_cg_bom.xml"

set cgPartSpec "xc6slx25-2ftg256"

set hdlType "VHDL"

# generate the IP
set result [source "i:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_reconfig_core.tcl"]

exit $result

